export const WilayaNames = {
    'w01': "Adrar",
    'w02': "Chlef",
    'w03': "Laghouat",
    'w04': "Oum El Bouaghi",
    'w05': "Batna",
    'w06': "Béjaïa",
    'w07': "Biskra",
    'w08': "Béchar",
    'w09': "Blida",
    'w10': "Bouira",
    'w11': "Tamanrasset",
    'w12': "Tébessa",
    'w13': "Tlemcen",
    'w14': "Tiaret",
    'w15': "Tizi Ouzou",
    'w16': "Alger",
    'w17': "Djelfa",
    'w18': "Jijel",
    'w19': "Sétif",
    'w20': "Saïda",
    'w21': "Skikda",
    'w22': "Sidi Bel Abbès",
    'w23': "Annaba",
    'w24': "Guelma",
    'w25': "Constantine",
    'w26': "Médéa",
    'w27': "Mostaganem",
    'w28': "M'Sila",
    'w29': "Mascara",
    'w30': "Ouargla",
    'w31': "Oran",
    'w32': "El Bayadh",
    'w33': "Illizi",
    'w34': "Bordj Bou Arreridj",
    'w35': "Boumerdès",
    'w36': "El Tarf",
    'w37': "Tindouf",
    'w38': "Tissemsilt",
    'w39': "El Oued",
    'w40': "Khenchela",
    'w41': "Souk Ahras",
    'w42': "Tipaza",
    'w43': "Mila",
    'w44': "Aïn Defla",
    'w45': "Naâma",
    'w46': "Aïn Témouchent",
    'w47': "Ghardaïa",
    'w48': "Relizane",
    'w49': "Timimoun",
    'w50': "Bordj Badji Mokhtar",
    'w51': "Ouled Djellal",
    'w52': "Béni Abbès",
    'w53': "In Salah",
    'w54': "In Guezzam",
    'w55': "Touggourt",
    'w56': "Djanet",
    'w57': "El Meghaier",
    'w58': "El Menia"
}